Api changes
intergiro/service-clearhaus pull request #58
Opened 2022-05-23 14:37 UTC by robinnedergard

2022-05-24 11:32 UTC, Magnus93 requested changes

2022-05-24 11:32 UTC, Magnus93 commented on api/Authorization/Request/InitialRecurring.ts
> +	series: "recurring" | "unscheduled"
The series type is more similar to:
```
{
  series: {
    type: "recurring" | "unscheduled",
    previous: {
      mastercard?: {type: string, exemption: string, tid: string},
      visa?: {type: string, tid: string},
      id?: string,
    },
  }
} 
```

2022-05-25 10:44 UTC, asnahassan approved these changes

2022-05-26 14:09 UTC, nilssonemma approved these changes

2022-05-30 07:17 UTC, Magnus93 approved these changes

2022-05-30 11:37 UTC, marcushanses approved these changes

2022-05-31 08:23 UTC, fredrikbryntesson approved these changes

2022-05-31 08:23 UTC, merged